cerebro:
  image:
    repository: "asia.gcr.io/sphong-kuber/cerebro"
    tag: "0.9.0"
    pullPolicy: "IfNotPresent"
  username: "admin"
  password: "1234"
  port: 9000
  replicaCount: 1
elasticsearch:
  strategy: "RollingUpdate"
  image:
    repository: "asia.gcr.io/sphong-kuber/elasticsearch-base"
    tag: "6.8.2"
    pullPolicy: "IfNotPresent"
  clusterName: "es-cluster"
  persistentEnable: true
  client:
    replicaCount: 1
    heapSize: "512m"
    additionalJavaOpts: ""
    resources:
      limits:
        cpu: "250m"
        memory: "1Gi"
  master:
    replicaCount: 3
    heapSize: "512m"
    additionalJavaOpts: ""
    resources:
      limits:
        cpu: "250m"
        memory: "1Gi"
  hot:
    replicaCount: 1
    heapSize: "512m"
    additionalJavaOpts: ""
    storage: "1Gi"
    resources:
      limits:
        cpu: "250m"
        memory: "2Gi"
  warm:
    replicaCount: 1
    heapSize: "512m"
    additionalJavaOpts: ""
    storage: "1Gi"
    resources:
      limits:
        cpu: "250m"
        memory: "1Gi"
kibana:
  image:
    repository: "asia.gcr.io/sphong-kuber/kibana"
    tag: "6.8.2"
    pullPolicy: "IfNotPresent"
cluster:
  userEmail: "user@email.com"
  managerEmail: "manager@email.com"
