apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "elasticsearch.name" . }}-data-hot
  labels:
    component: elasticsearch
    role: data
spec:
  replicas: {{ .Values.elasticsearch.hot.replicaCount }}
  serviceName: {{ include "elasticsearch.name" . }}-data
  selector:
    matchLabels:
      component: elasticsearch
      role: data 
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
    spec:
      containers:
      - name: {{ include "elasticsearch.name" . }}-data-hot
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: "{{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}"
        args:
        - /run.sh
        - -Enode.attr.box_type=hot 

        readinessProbe:
          tcpSocket:
            port: 9300
          timeoutSeconds: 60
          successThreshold: 1
        imagePullPolicy: {{ .Values.elasticsearch.image.pullPolicy }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: es-env
              key: es-cluster-name
        - name: NODE_MASTER
          value: 'false'
        - name: NODE_DATA
          value: 'true'
        - name: NODE_INGEST
          value: 'true'
        - name: HTTP_ENABLE
          value: 'false'
        - name: ES_JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: es-env
              key: es-hot-java-opts
        - name: ES_CLIENT_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: es-env
              key: es-client-endpoint
        - name: ES_PERSISTENT
          valueFrom:
            configMapKeyRef:
              name: es-env
              key: es-persistent-storage
        ports:
        - name: transport
          containerPort: 9300
          protocol: TCP
        # Random hostPort to prevent multiple ES data instances on one node
        - name: dummy
          containerPort: 28652
          protocol: TCP
          hostPort: 28652
        volumeMounts:
        - name: data
          mountPath: /data
        - name: es-config
          mountPath: /elasticsearch/conf

      terminationGracePeriodSeconds: 30

      volumes:
      - name: es-config
        configMap:
          name: es-config

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: ssd
        resources:
          requests:
            storage: {{ .Values.elasticsearch.hot.storage }}
