apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch.name" . }}-data
  labels:
    component: elasticsearch
    role: data
spec:
  selector:
    component: elasticsearch
    role: data
  clusterIP: None
  ports:
  - name: transport
    port: 9300
    protocol: TCP
