apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch.name" . }}-discovery
  labels:
    component: elasticsearch
    role: master    
spec:
  selector:
    component: elasticsearch
    role: master
  clusterIP: None
  ports:
  - name: transport
    port: 9300
    protocol: TCP
