apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "elasticsearch.name" . }}-master
  labels:
    instance: "elasticsearch-manager"
    component: elasticsearch
    role: master

spec:
  replicas: {{ .Values.elasticsearch.master.replicaCount }}
  selector:
    matchLabels:
      instance: "elasticsearch-manager"
      component: elasticsearch
      role: master

  strategy:
    type: {{ .Values.elasticsearch.strategy }}
  template:
    metadata:
      labels:
        instance: "elasticsearch-manager"
        component: elasticsearch
        role: master

    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-node-pool
      containers:
      - name: {{ include "elasticsearch.name" . }}-master
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK

        image: "{{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag}}"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
{{ toYaml .Values.elasticsearch.master.resources | indent 10 }}

        readinessProbe:
          tcpSocket:
            port: 9300
          timeoutSeconds: 60
          successThreshold: 1
        imagePullPolicy: {{ .Values.elasticsearch.image.pullPolicy }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: es-env
              key: es-cluster-name
        - name: NETWORK_HOST
          value: 0.0.0.0
        - name: NODE_MASTER
          value: 'true'
        - name: NODE_DATA
          value: 'false'
        - name: NODE_INGEST
          value: 'true'
        - name: HTTP_ENABLE
          value: 'true'
        - name: ES_JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: es-env
              key: es-master-java-opts
        - name: ES_CLIENT_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: es-env
              key: es-client-endpoint
        ports:
        - name: transport
          containerPort: 9300
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /data
        - name: es-config
          mountPath: /elasticsearch/conf

      terminationGracePeriodSeconds: 10

      volumes:
      - name: data
        emptyDir: {}
      - name: es-config
        configMap:
          name: es-config
