apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch.name" . }}-client
  labels:
    component: elasticsearch
spec:
  selector:
    instance: "elasticsearch-manager"
    component: elasticsearch
    role: client
  type: LoadBalancer
  ports:
  - name: http
    port: 9200
    protocol: TCP
